camera_interface/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('user.urls', namespace='user')),
    path('interface/', include('interface.urls', namespace='interface')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

interface/urls.py
from django.urls import path
from . import views



app_name = "interface"

urlpatterns = [
    path('digital_camera/', views.digital_camera, name='digital_camera'),
    path('stream_video/', views.stream_video, name='stream_video'),
    path('save_screenshot/', views.save_screenshot, name='save_screenshot'),
    path('example_view/', views.example_view, name='example_view'),
    path('capture_frames/', views.capture_frames, name='capture_frames'),
    path('send_files/', views.send_files_to_server, name='send_files'),
    path('control/', views.control_page, name='control_page'),
    path('save_car_part/', views.save_car_part, name='save_car_part'),
    path('get_photos_by_article/', views.get_photos_by_article, name='get_photos_by_article'),
    path('roster_page/', views.roster_page, name='roster_page'),
    path('roster_page/<str:selected_date>/', views.roster_page, name='roster_page_with_date'),
    path('get_car_parts_json/', views.get_car_parts_json, name='get_car_parts_json'),
    path('delete_matching_article/', views.delete_matching_article_view, name='delete_matching_article'),

    # ...

]

user/urls.py
from django.urls import path
from . import views
from .views import logout_view

app_name = 'user'
urlpatterns = [
    path('', views.login_view, name='login'),
    # Другие URL-шаблоны вашего приложения
    path('logout/', logout_view, name='logout'),
]

interface/models.py
from django.db import models
from datetime import datetime


class CarPart(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    article_number = models.CharField(max_length=50, unique=True, verbose_name='Артикул')
    place = models.CharField(max_length=50, verbose_name='Место', default='')
    added_time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name

    def matching_articles(self):
        return MatchingArticle.objects.filter(article_number=self.article_number)

    def all_photos(self):
        photos = Photo.objects.filter(car_part__article_number=self.article_number)
        matching_articles = self.matching_articles()
        for ma in matching_articles:
            photos |= Photo.objects.filter(car_part__article_number=ma.article_number)
        return photos

class MatchingArticle(models.Model):
    article_number = models.CharField(max_length=50, unique=True)
    added_time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.article_number


class Photo(models.Model):
    car_part = models.ForeignKey(CarPart, on_delete=models.CASCADE, related_name='photos', verbose_name='Запчасть')
    image_url = models.URLField(max_length=200, verbose_name='URL фотографии', default='')

    def __str__(self):
        return f"Фото {self.car_part.name}"

class VerifiedArticle(models.Model):
    article_number = models.CharField(max_length=50, unique=True)
    added_time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.article_number

interface/forms.py
from django import forms
from .models import CarPart

class CarPartForm(forms.ModelForm):
    class Meta:
        model = CarPart
        fields = ['name', 'article_number', 'place']

interface/views.py
import cv2
import time
import asyncio
from django.http import HttpResponse, StreamingHttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt, csrf_protect
import paramiko
import os
from .models import CarPart, Photo, MatchingArticle, VerifiedArticle
from queue import Queue
import numpy as np
from .forms import CarPartForm
from django.contrib.auth.decorators import user_passes_test
import boto3
from botocore.exceptions import NoCredentialsError
import shutil
from django.utils import timezone
from datetime import datetime
from .json_utils import CustomJSONEncoder
import json

AWS_S3_ACCESS_KEY_ID = 'YCAJED2HUj8DMX6N6ROlMjD4O'
AWS_S3_SECRET_ACCESS_KEY = 'YCMZKYsIcf9dQN7MC_Hoe9-8mQhZcxusZb4VeZu1'
AWS_STORAGE_BUCKET_NAME = 'meff1986'
AWS_S3_ENDPOINT_URL = 'https://storage.yandexcloud.net'


# Глобальные переменные
camera_numbers = [1, 2, 3, 4, 5, 6, 7]
folder_number = 1
screenshot_counter = 1
value = None
# Добавьте словарь для хранения последних кадров с каждой камеры
last_frames = {}
s3 = boto3.client(
    's3',
    aws_access_key_id='YCAJED2HUj8DMX6N6ROlMjD4O',
    aws_secret_access_key='YCMZKYsIcf9dQN7MC_Hoe9-8mQhZcxusZb4VeZu1',
    endpoint_url='https://storage.yandexcloud.net'

)
bucket_name = 'meff1986'

def stream_video(request):
    camera = int(request.GET.get('camera', 1))

    # Открываем видеопоток с указанной камеры
    cap = cv2.VideoCapture(camera)

    # Установка разрешения видео
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)
    cap.set(cv2.CAP_PROP_AUTOFOCUS, 1)

    def generate_frames():
        try:
            while True:
                ret, frame = cap.read()

                if not ret:
                    break

                # Преобразуем кадр в формат JPEG
                _, jpeg = cv2.imencode('.jpg', frame)

                # Сохраняем последний кадр в словаре
                last_frames[camera] = frame

                # Возвращаем кадр как генератор байтовых данных
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + jpeg.tobytes() + b'\r\n\r\n')
        except GeneratorExit:
            pass

    return StreamingHttpResponse(generate_frames(), content_type='multipart/x-mixed-replace; boundary=frame')


def capture_frames(request):
    frame_interval = 0.35
    max_time = 22.5
    start_time = time.time()
    i = 0

    position_value = request.POST.get('front_value')
    current_time = datetime.now().strftime("%Y_%m_%d")
    folder_name = f"{current_time}_{value}"  # Replace 'temp_dir' with the desired temporary directory path
    folder_path = os.path.join(folder_name)
    os.makedirs(folder_path, exist_ok=True)

    while (time.time() - start_time) < max_time:
        i += 1

        # Ожидаем получения нового кадра из каждого видеопотока
        time.sleep(frame_interval)

        # Получаем последний доступный кадр из каждого видеопотока
        frame1 = last_frames[5]
        frame2 = last_frames[2]
        frame3 = last_frames[3]
        frame4 = last_frames[3]

        # Создаем экземпляр модели Photo и ассоциируем его с моделью CarParts
        car_part = CarPart.objects.get(article_number=value) if value else None


        # Создаем и сохраняем фотографии
        for frame_number, frame in enumerate([frame1, frame2, frame3, frame4], start=1):
            current_time = datetime.now().strftime("%Y_%m_%d")

            filename = f'{value}_{position_value}_{i}_{frame_number}.jpg'
            filepath = f'{current_time}_{value}/{filename}'


            # Сохраняем кадр как изображение
            cv2.imwrite(filepath, frame)
            s3_path = f"{filepath}"
            s3.upload_file(filepath, bucket_name, s3_path)

            # Проверяем, существует ли уже объект Photo с таким image_url
            existing_photo = Photo.objects.filter(image_url='https://storage.yandexcloud.net/meff1986/' + s3_path).first()
            if not existing_photo:
                # Если объекта Photo с таким image_url нет, то создаем новый объект
                photo = Photo.objects.create(car_part=car_part, image_url='https://storage.yandexcloud.net/meff1986/' + s3_path)

            # Удаляем локальный файл после успешной загрузки на S3

    shutil.rmtree(folder_path)
    return JsonResponse({'success': True})


def example_view(request):
    global value
    if request.method == 'POST':
        value = request.POST.get('value')

        if value:
            matching_car_part = CarPart.objects.filter(article_number=value).first()

            if matching_car_part:
                matching_article, created = MatchingArticle.objects.get_or_create(
                    article_number=matching_car_part.article_number)
            else:
                error_message = 'Вы ввели неправильный артикул'
                print(error_message)
                return JsonResponse({'error_message': error_message})  # Возвращаем сообщение об ошибке в AJAX-ответ

        matching_articles = MatchingArticle.objects.all()
        return render(request, 'interface/control_page.html', {'matching_articles': matching_articles})

    return render(request, 'interface/digital_camera.html')


@csrf_exempt
def save_screenshot(request):
    global folder_number, screenshot_counter, value

    # Открываем видеопоток с первой камеры
    camera = 1
    cap = cv2.VideoCapture(camera)

    # Установка разрешения видео
    cap.set(cv2.CAP_PROP_AUTOFOCUS, 1)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 720)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1280)


    cap.set(cv2.CAP_PROP_AUTOFOCUS, 1)
    time.sleep(10)
    ret, frame = cap.read()
    if not ret:
        cap.release()  # Освобождаем ресурсы камеры
        return HttpResponse('Failed to capture a frame from camera.')



    # Если получен кадр, сохраняем его как изображение
    if ret:
        try:
            # Create a folder if it doesn't exist
            current_time = datetime.now().strftime("%Y_%m_%d")

            folder_name = f"{current_time}_{value}"  # Replace 'temp_dir' with the desired temporary directory path
            folder_path = os.path.join(folder_name)
            os.makedirs(folder_path, exist_ok=True)


            # Save the frame as an image file with a unique name, including the article number if available
            if value:
                filename = f"article_{screenshot_counter}_{value}.jpg"
            else:
                filename = f"article_{screenshot_counter}.jpg"

            filepath = os.path.join(folder_path, filename)
            cv2.imwrite(filepath, frame)
            s3_path = f"{folder_name}/{filename}"
            s3.upload_file(filepath, bucket_name, s3_path)
            # Increment the screenshot counter
            screenshot_counter += 1

            car_part = CarPart.objects.get(article_number=value) if value else None
            existing_photo = Photo.objects.filter(image_url='https://storage.yandexcloud.net/meff1986/' + s3_path).first()
            if not existing_photo:
                # Если объекта Photo с таким image_url нет, то создаем новый объект
                photo = Photo.objects.create(car_part=car_part,
                                             image_url='https://storage.yandexcloud.net/meff1986/' + s3_path)

            # If the 'OK' button is clicked in the modal dialog, create a new folder for the next screenshots
            if request.POST.get('button') == 'OK':
                folder_number += 1
                screenshot_counter = 1

        finally:
            cap.release()  # Освобождаем ресурсы камеры
            shutil.rmtree(folder_path)  # Удаляем временную папку

        # Return a response indicating success
        return HttpResponse('Screenshot saved successfully.')
    else:
        cap.release()  # Освобождаем ресурсы камеры
        return HttpResponse('Failed to capture a frame from camera 1.')



@csrf_exempt
def send_files_to_server(request):
    local_path = "D:/digital"
    server_ip = "95.163.233.68"
    server_login = "root"
    server_password = "Mrhk%3+#yuqx"
    remote_path = "/var/Foto/"

    # Create SSH client
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        # Connect to server
        ssh.connect(server_ip, username=server_login, password=server_password)

        # Create remote destination folder if it does not exist
        ssh.exec_command(f"mkdir -p {remote_path}")

        for root, dirs, files in os.walk(local_path):
            for file in files:
                local_file_path = os.path.join(root, file)
                relative_path = os.path.relpath(local_file_path, local_path)
                remote_file_path = os.path.join(remote_path, relative_path)

                # Create remote directories if they do not exist
                ssh.exec_command(f"mkdir -p {os.path.dirname(remote_file_path)}")

                sftp = ssh.open_sftp()
                sftp.put(local_file_path, remote_file_path)
                sftp.close()

    except paramiko.AuthenticationException:
        print("Authentication error. Please check your credentials.")
        return JsonResponse({'success': False, 'error': 'Authentication error. Please check your credentials.'},
                            status=500)
    except paramiko.SSHException as ssh_exception:
        print(f"SSH error: {ssh_exception}")
        return JsonResponse({'success': False, 'error': f'SSH error: {ssh_exception}'}, status=500)
    except Exception as e:
        print(f"Error: {e}")
        return JsonResponse({'success': False, 'error': f'Error: {e}'}, status=500)
    finally:
        ssh.close()

    return JsonResponse({'success': True})


def digital_camera(request):
    if request.user.groups.filter(name='Контролеры').exists():
        return redirect('interface:control_page')
    return render(request, 'interface/digital_camera.html')





def save_car_part(request):

interface/templates/interface/control.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Экран проверки</title>
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="stylesheet" type="text/css" href="{% static 'interface/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'interface/css/normalize.css' %}">
    <script src="{% static 'interface/js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body class="body__control">
    {% block content %}
    <main class="site-main control">
        <nav class="nav">
            <ul class="nav__list">
                <li class="nav__item "><a href="/index.html">Экран оцифровки запчасти</a></li>
                <li class="nav__item"><a href="/auto-parts.html">Список запчастей</a></li>
                <li class="nav__item current-page"><a href="#">Экран проверки</a></li>
                <li class="nav__item"><a href="/login.html">Выход</a></li>
            </ul>
        </nav>
        <h1 class="visually-hidden">Экран оцифровки запчасти</h1>
        <section class="control__process">
            <div class="control__user process_wrapper">
                <div class="control__user-name">Пользователь: Иванов ИИ</div>
                <div class="control__user-task"><a class="button control__button control__user-task-link button-show" href="#">Задание оператору</a></div>
            </div>
            <form class="control_form-article" action="#" method="post">
                <fieldset class="control__fieldset-textarea" style="height: 200px; overflow: auto;">
                 <div class="">
                    <p>Дата оцифровки:<input type="date"></p>
                    <ol >
                        <li></li>
                        <li></li>
                        <li></li>
                    </ol>

                </div>
                </fieldset>
                <fieldset class="current-point">
                     <p>1. Проверка артикула </p>
                    <div class="process-evenly_wrapper">
                    <button class="button control__button control__button-agree" >совпадает</button>
                    <button class="button control__button control__button-disagree">не совпадает</button>
                    <label class="control__process-input-label-article" for="article"></label>
                    <input class="control__checkbox checkbox-article" type="checkbox" name="done" id="article">
                    </div>
                </fieldset>
                </form>
                <form class="control__process-form-photo" action="#" method="post">
                    <fieldset>
                       <p>2. Качество фотоматериала</p>
                       <div class="process_wrapper">
                        <label class="control__process-input-label-article" for="">2.1. фото артикула</label>
                        <input class="control__checkbox checkbox-article" type="checkbox" name="" id="">
                        <button class="button control__button control__button-disagree">переснять</button>
                       </div>
                       <div class="process_wrapper">
                        <label class="control__process-input-label-article" for="">2.2. лицевая часть</label>
                        <input class="control__checkbox checkbox-article" type="checkbox" name="" id="">
                        <button class="button control__button control__button-disagree">переснять</button>
                       </div>
                       <div class="process_wrapper">
                        <label class="control__process-input-label-article" for="">2.3. тыльная часть</label>
                        <input class="control__checkbox checkbox-article" type="checkbox" name="" id="">
                        <button class="button control__button control__button-disagree">переснять</button>
                       </div>
                       <div class="process_wrapper">
                        <label class="control__process-input-label-article" for="">2.4. доп. фотографии</label>
                        <input class="control__checkbox checkbox-article" type="checkbox" name="" id="">
                        <button class="button control__button control__button-disagree">переснять</button>
                       </div>
                    </fieldset>
                    <fieldset>
                        <div class="process_wrapper">
                        <p>3. Следующая деталь</p>
                        <div class="button_padding-right">
                        <a class="control__process-back" href="#"><img src="./img/back.svg" height="45" width="45" alt="back"></a>
                        <a class="control__process-next" href="#"><img src="./img/next.svg" height="45" width="45" alt="next"></a>
                        </div>
                        </div>
                    </fieldset>
                    <fieldset class="process_wrapper">
                        <p>4. Отчет по проверки</p>
                        <button class="button control__button control__button-finish">Распечатать и отправить<br> Задание оператору </button>
                    </fieldset>
                </form>
        </section>
        <section class="control__camera">
            <form class="control__camera-form" action="#" method="post">
                <p class="control__camera-heading">Экран камеры</p>
                <div class="control_video-wrapper">
                    <div class="control_video-1">
                      <img  src="{% url 'stream_video' %}" width="320" height="240">
                      <a class="control_video-full-1" href="#"><img  src="./img/full_screen.svg" width="40" height="40"></a>
                    </div>   
                    <div class="control_video-2">
                        <img  src="{% url 'stream_video' %}" width="320" height="240">
                        <a class="control_video-full-2" href="#"><img  src="./img/full_screen.svg" width="40" height="40"></a>
                      </div>
                      <div class="control_video-3">
                        <img  src="{% url 'stream_video' %}" width="320" height="240">
                        <a class="control_video-full-3" href="#"><img  src="./img/full_screen.svg" width="40" height="40"></a>
                      </div>
                      <div class="control_video-4">
                        <img  src="{% url 'stream_video' %}" width="320" height="240">
                        <a class="control_video-full-4" href="#"><img  src="./img/full_screen.svg" width="40" height="40"></a>
                      </div>          
                    </div>              
            </form>       
        </section>
        <section class="modal-page modal-control">
            <form class="control-form" action="#" method="post">
              <div class="wrapper-modal">
                <div class="modal_input">
                   <label for="modal-article">Артикул</label>
                   <input class="control-modal-article" type="text" name="modal-article" id="modal-article" placeholder="6RU 987 986 1" autofocus=""> 
                </div>
                <div class="modal_input">
                    <label for="modal-name">Название</label>
                    <input class="control-modal-name" type="text" name="modal-name" id="modal-name" placeholder="Крыло переднее правое" autofocus="">
                </div>
                <div class="modal_input">
                   <label for="modal-place">Место</label>
                <input class="control-modal-place" type="text" name="modal-place" id="modal-place" placeholder="3с-34-2-1" autofocus=""> 
                </div>
               </div> 
               <div class="button_modal-submit">
                <button class="button" type="submit">Отправить</button>
               </div>
               <a class="modal-close button-hide" type="button" aria-label="Закрыть"></a>
              </form>
          </section>
    </main>
    {% endblock %}
    <script>
        const modalControl = document.querySelector('.modal-control');
        const openModalControl = document.querySelector('.button-show');
        const closeModalControl  = modalControl.querySelector('.button-hide');
        let isStorageSupport = true;
        let storage = "";

try {
  storage = localStorage.getItem("modal-article");
} catch (err) {
  isStorageSupport = false;
};

openModalControl.addEventListener('click', function(evt) {
  evt.preventDefault();
  modalControl.classList.add('modal-open');

});

closeModalControl.addEventListener('click', function(evt) {
  evt.preventDefault();
  modalControl.classList.remove('modal-open');
});


document.addEventListener('keydown', function(evt){
  if (evt.keyCode === 27){
    modalControl.classList.remove('modal-open');
    }
});
    </script>
</body>
</html>

interface/templates/interface/roster_page.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список запчастей</title>
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="stylesheet" type="text/css" href="{% static 'interface/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'interface/css/normalize.css' %}">
    <script src="{% static 'interface/js/script.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<style>
@media print {
    .hidden-row {
        display: none !important;
    }
}
</style>
</head>

<body class="body__roster">
    {% block content %}
    <main class="site-main roster">
        <nav class="nav">
            <ul class="nav__list">
                <li class="nav__item "><a href="{% url 'interface:digital_camera' %}">Экран оцифровки запчасти</a></li>
                <li class="nav__item current-page"><a href="#">Список запчастей</a></li>
                <li class="nav__item"><a href="{% url 'interface:control_page' %}">Экран проверки</a></li>
                <li class="nav__item"><a href="{% url 'user:logout' %}">Выход</a></li>
            </ul>
        </nav>
        <div class="roster-wrapper">
        <h1 class="visually-hidden">Экран оцифровки запчасти</h1>
        <section class="roster__process">
            <div class="roster__user process_wrapper">
                <div class="roster__user-name">Пользователь: {{ request.user.username }}</div>
                <div class="roster__user-task"><a class="button roster__button" href="#">Задание оператору</a></div>
            </div>
            <div class="process_wrapper">
                <button class="button roster__button">Список запчастей для оцифровки</button>
                <button class="button roster__button" id="print-button">Распечатать</button>
            </div>
        </section>
        <section class="roster__table">
          <table class="table" width="100%" border="1" cellspacing="0" cellpadding="4">
            <thead>
                <tr class="table__row">
                    <th class="table__header">№</th>
                    <th class="table__header">1. Артикул</th>
                    <th class="table__header">2. Название</th>
                    <th class="table__header">3. Место</th>
                    <th class="table__header">4. Дата добавления</th>
                </tr>
            </thead>
            <tbody id="table-body">
                {% for car_part in car_parts %}
                <tr class="table__row {% if car_part.article_number in matching_articles %}hidden-row{% endif %}">
                    <td class="table__data">{{ forloop.counter }}</td>
                    <td class="table__data" data-article="{{ car_part.article_number }}">{{ car_part.article_number }}</td>
                    <td class="table__data">{{ car_part.name }}</td>
                    <td class="table__data">{{ car_part.place }}</td>
                    <td class="table__data">{{ car_part.added_time}}</td>
                </tr>
                {% endfor %}
          </tbody>
        </table>
        </section>
        </div>
    </main>
    {% endblock %}
 <script>
$(document).ready(function() {
  const selectedDateInput = document.getElementById('selected-date');
  const tableBody = document.getElementById('table-body'); // Получаем tbody по id

  selectedDateInput.addEventListener('change', function() {
    const selectedDate = selectedDateInput.value;
    console.log('Выбранная дата:', selectedDate);


    $.ajax({
      url: `/interface/roster_page/?date=${selectedDate}`,
      type: 'GET',
      dataType: 'json',
      success: function(response) {
        updateTable(response.car_parts);
      },
      error: function(xhr, errmsg, err) {
        console.log(xhr.status + ': ' + xhr.responseText);
      }
    });
  });

  function updateTable(carParts) {
    tableBody.innerHTML = ''; // Очищаем tbody

    carParts.forEach(function(carPart, index) {
      const row = `
        <tr class="table__row">
          <td class="table__data">${index + 1}</td>
          <td class="table__data" data-article="${carPart.article_number}">${carPart.article_number}</td>
          <td class="table__data">${carPart.name}</td>
          <td class="table__data">${carPart.place}</td>
          <td class="table__data">${carPart.added_time}</td>
        </tr>
      `;
      tableBody.insertAdjacentHTML('beforeend', row);
    });
  }

  const matchedArticles = "{{ matching_articles|join:',' }}";  // Получаем значения из контекста
  console.log('Значение matchedArticles:', matchedArticles);
$(document).ready(function() {
  const matchedArticles = "{{ matched_articles }}";  // Получаем значение из контекста

  if (matchedArticles) {
    const table = document.querySelector(".table");  // Выбираем таблицу
    const rows = table.querySelectorAll(".table__row");  // Выбираем строки таблицы

    // Проходимся по всем строкам и скрываем те, где артикул совпал
    rows.forEach(row => {
      const articleCell = row.querySelector(".table__data[data-article]");
      if (articleCell && matchedArticles.includes(articleCell.textContent)) {
        row.style.display = "none";
      }
    });
  }
});

$(document).ready(function() {
    var removeHiddenRow = localStorage.getItem('removeHiddenRow');
    if (removeHiddenRow) {
        $(".table__row[data-article='" + removeHiddenRow + "']").removeClass("hidden-row");
        localStorage.removeItem('removeHiddenRow');
    }
});
document.addEventListener('DOMContentLoaded', function () {
    // Получаем ссылку на кнопку "Распечатать"
    var printButton = document.getElementById('print-button');

    // Добавляем обработчик события клика на кнопку
    printButton.addEventListener('click', function () {
        // Получаем ссылку на таблицу
        var table = document.querySelector('.roster__table table');

        // Открываем новое окно для печати
        var printWindow = window.open('', '_blank');

        // Вставляем HTML содержимое таблицы в новое окно
        printWindow.document.write('<html><head><title>Печать</title></head><body>');
        printWindow.document.write(table.outerHTML);
        printWindow.document.write('</body></html>');

        // Печатаем содержимое нового окна
        printWindow.print();

        // Закрываем новое окно после печати
        printWindow.close();
    });
});

</script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var printButton = document.getElementById('print-button');
    printButton.addEventListener('click', function () {
        var table = document.querySelector('.roster__table table');

        var cloneTable = table.cloneNode(true); // Создаем копию таблицы

        var hiddenRows = cloneTable.querySelectorAll('.hidden-row');
        hiddenRows.forEach(function(row) {
            row.parentNode.removeChild(row); // Удаляем скрытые строки из копии таблицы
        });

        var printWindow = window.open('', '_blank');

        printWindow.document.write('<html><head><title>Печать</title></head><body>');
        printWindow.document.write(cloneTable.outerHTML); // Печатаем копию таблицы
        printWindow.document.write('</body></html>');

        printWindow.print();
        printWindow.close();
    });
});
</script>
</body>